[server]

# The server name
# paper, velocity, waterfall
project = "paper"

# The server version
# if you use always latest version, set "latest"
version = "1.20.2"

# The server build
# if you use always latest build, set "latest"
build = "latest"

# file name of the server jar
file = "server.jar"

# stop command
stop = "stop"

# restart time
# 分単位
restart = 5

[java]
# java command
command = "java"

# memory size
memory = "1G"

[develop]
# DEBUG mode
# if you want to see the debug log, set true
debug = false

# log file
logfile = "mcm.log"

[database]
# The database file
name = "mcm.db"

[discord]
enable = true
webhook_url = "https://discord.com/api/webhooks/1182221233731944528/PoDbiq_953NtLSnRp2-dTPZxXwADm-yKUgT2_Jqag73ouJVJZNvThhFogdfNRiDvnoq8"
